--OPERATOR
--ARITHMATIC -- +,-,*,/
--RELATIONAL -- <,>,<=,>=,=,NOT EQUAL (!=,<>,NOT)
--LOGICAL -- AND OR NOT
--SPECIAL -- IS IN BETWEEN LIKE
--CONCAT -- ||
--

CREATE TABLE STUDENT_INF (STUD_ID NUMBER , STUD_FNAME VARCHAR(15),STUD_LNAME VARCHAR(20))

DROP TABLE STUDENT_INF;

INSERT INTO STUDENT_INF(STUD_ID, STUD_FNAME, STUD_LNAME)VALUES(1,'RUSHI','JANKAR');
INSERT INTO STUDENT_INF(STUD_ID, STUD_FNAME, STUD_LNAME)VALUES(2,'ROHIT','SHARMA');
INSERT INTO STUDENT_INF(STUD_ID, STUD_FNAME, STUD_LNAME)VALUES(3,'VIRAT','KOHLI');
INSERT INTO STUDENT_INF(STUD_ID, STUD_FNAME, STUD_LNAME)VALUES(4,'RISHAB','PANT');

ALTER TABLE STUDENT_INF ADD SUB1_MARK NUMBER;
ALTER  TABLE STUDENT_INF ADD  SUB2_MARK NUMBER;

UPDATE  STUDENT_INF SET SUB1_MARK = 30 WHERE STUD_ID =1;
UPDATE  STUDENT_INF SET SUB1_MARK = 20 WHERE STUD_ID IN (2,4);

UPDATE STUDENT_INF SET SUB2_MARK = 40 WHERE STUD_ID IN(1,3);
UPDATE STUDENT_INF SET SUB2_MARK = 23 WHERE STUD_ID IN(2,4);


--ARITHMATIC
SELECT 2+2 FROM DUAL;
SELECT 2-1 FROM DUAL ;
SELECT 2*3 FROM DUAL;
SELECT 4/2 FROM DUAL ;
SELECT NULL - 1 FROM DUAL;

SELECT SUB1_MARK +SUB2_MARK FROM STUDENT_INF WHERE STUD_ID = 3;  // ANY ARTHMATICAL OPERATION WITH NULL RESULT WILL BE NULL BZ UNDEFINED VALUES OF NULL

SELECT SUB1_MARK + SUB2_MARK FROM STUDENT_INF;
SELECT SUM(SUB1_MARK + SUB2_MARK) FROM STUDENT_INF;
SELECT COUNT(*) FROM STUDENT_INF;
SELECT SUM(SUB1_MARK + SUB2_MARK)/COUNT(STUD_ID) FROM STUDENT_INF;
SELECT SUM(SUB1_MARK) FROM STUDENT_INF;
SELECT AVG(SUB1_MARK) AS DEMO FROM STUDENT_INF ; // ALWAY AVG FUN IGNORE NULL RECORD

--"-"
SELECT SUB1_MARK - SUB2_MARK FROM STUDENT_INF WHERE stud_id IN (1);

--
SELECT SUB1_MARK * SUB2_MARK FROM STUDENT_INF;


-------------RELATIONAL----------
-->
SELECT * FROM STUDENT_INF WHERE STUD_ID>2;
SELECT * FROM STUDENT_INF WHERE STUD_ID>=2;

SELECT * FROM STUDENT_INF WHERE SUB1_MARK >50;

SELECT STUD_ID FROM STUDENT_INF WHERE SUB1_MARK>20;

SELECT * FROM STUDENT_INF WHERE STUD_ID = 2;
SELECT * FROM STUDENT_INF WHERE SUB1_MARK = 20;
SELECT * FROM STUDENT_INF WHERE STUD_ID <> 1;
SELECT * FROM STUDENT_INF WHERE SUB1_MARK !=20;
SELECT * FROM STUDENT_INF WHERE SUB1_MARK !=NULL;
SELECT * FROM STUDENT_INF WHERE SUB1_MARK = NULL;
SELECT * FROM STUDENT_INF WHERE STUD_ID NOT IN(1,2,3);


---LOGICAL 
-- AND OR NOT

SELECT * FROM STUDENT_INF WHERE  STUD_ID = 2 AND STUD_ID = 4;// RESULT 0 ID NOT SATISFY 2 CONDITIONS
SELECT * FROM STUDENT_INF WHERE STUD_ID= 2 AND SUB2_MARK = 23;
SELECT * FROM STUDENT_INF WHERE STUD_ID = 12 OR STUD_ID=3;
SELECT * FROM STUDENT_INF WHERE STUD_ID NOT IN(1,2,3);
SELECT * FROM STUDENT_INF WHERE SUB2_MARK NOT IN(20,10,30);

--SPECIAL
-- IS IN BETWEEN LIKE

--IS

--IN 
SELECT STUD_FNAME FROM STUDENT_INF WHERE SUB1_MARK IN (20,30,40);
SELECT STUD_FNAME , STUD_LNAME FROM STUDENT_INF WHERE STUD_ID IN (1,3,4);


--BETWEEN 
SELECT * FROM STUDENT_INF WHERE STUD_ID BETWEEN 1 AND 3;
SELECT * FROM STUDENT_INF WHERE SUB1_MARK BETWEEN NULL AND 0;
SELECT * FROM STUDENT_INF WHERE SUB2_MARK BETWEEN 10 AND 30;

--LIKE

SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE '%R%';
SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE 'R%' OR STUD_FNAME LIKE '%T';
SELECT * FROM STUDENT_INF WHERE STUD_LNAME LIKE 'J%' AND STUD_FNAME LIKE '%I';
SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE '__S%';
SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE 'R__%';


SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE 'RUSHI';
SELECT * FROM STUDENT_INF WHERE STUD_FNAME LIKE 'R%I';
SELECT * FROM STUDENT_INF WHERE STUD_FNAME NOT LIKE 'R%';




---


SELECT * FROM STUDENT_INF;
DESC STUDENT_INF;
--ARITHMATIC