
--DATA TYPE -------leave 



--DATA TYPE

--CHAR()
--VARCHAR()
--NUMBER -- INT 
--DATE()




----ORDER BY-----
CREATE TABLE EMP ( EMP_ID NUMBER , EMP_FNAME VARCHAR(20) , EMP_LNAME VARCHAR(20), EMP_AGE NUMBER ,EMP_SALARY NUMBER, EMP_JOININGDATE DATE );

INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(1,'RUSHI','JANKAR',24, 45000, '10-JAN-2021'); 
INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(4,'SHYAM','JANKAR',35, 2000, '15-MAR-2023'); 
INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(3,'ROHIT','SHARMA',45, 65000, '01-FEB-2024'); 
INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(2,'PRATIKSHA','CHAUDHAR',36, 5000, '11-DEC-2022');
INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(0,'PRATIKSHAAA','DESAI',30, 50000, '01-DEC-2022');

INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(11,'REMO','PAWAR',NULL, 53000, '22-DEC-2022');
INSERT INTO EMP ( EMP_ID  , EMP_FNAME , EMP_LNAME, EMP_AGE ,EMP_SALARY, EMP_JOININGDATE) VALUES(NULL,'MRUNAL','DIXIT',30, 50000, '01-DEC-2022');
--ORDER BY EMPID
SELECT * FROM EMP ORDER BY emp_id;
SELECT * FROM EMP ORDER BY EMP_ID DESC;
SELECT * FROM EMP ORDER BY 1; // COLUMN SEQUENCE

--ORDER BY EMP_NAME
SELECT * FROM EMP ORDER BY EMP_FNAME ASC;
SELECT * FROM EMP ORDER BY EMP_FNAME DESC;

---ORDER BY LNAME
SELECT * FROM EMP ORDER BY EMP_LNAME ASC;
SELECT * FROM EMP ORDER BY EMP_LNAME ASC;

---ORDER BY AGE 
SELECT * FROM EMP ORDER BY EMP_AGE;
SELECT * FROM EMP ORDER BY 4;
SELECT EMP_AGE, EMP_ID FROM EMP ORDER BY EMP_AGE, EMP_ID;

---ORDER BY DATE
SELECT * FROM EMP ORDER BY emp_joiningdate;


--ORDER BY COLUMN NOT IN SELET LIST
SELECT EMP_ID , EMP_FNAME , EMP_LNAME FROM EMP ORDER BY EMP_AGE;


--ORDER BY USING EXPRESSION

--LENGHT
SELECT * FROM EMP ORDER BY LENGTH(EMP_FNAME); 

SELECT * FROM EMP ORDER BY LENGTH(EMP_ID);

SELECT LENGTH(EMP_ID) FROM EMP;

SELECT * FROM EMP ORDER BY LENGTH (emp_joiningdate);

--
SELECT * FROM EMP WHERE EMP_FNAME IN('RUSHI','SHYAM') ORDER BY EMP_ID ASC;
SELECT * FROM EMP WHERE EMP_FNAME IN('RUSHI','SHYAM') ORDER BY EMP_ID desc;

---ORDET BY NULL VALUES
SELECT * FROM EMP ORDER BY EMP_ID; // IN ASC NULL ALWAYS AT LAST POS
SELECT * FROM EMP ORDER BY EMP_ID DESC; // IN DESC NULL AT TOP POS

SELECT * FROM EMP ORDER BY EMP_ID NULLS FIRST;
SELECT * FROM EMP ORDER BY EMP_ID NULLS LAST;

SELECT * FROM EMP ORDER BY NULLS;


SELECT * FROM EMP ORDER BY 1;


SELECT * FROM EMP;
DROP TABLE EMP;

----OPERATOR 
--LOGICAL 
--ARITHMATIC


