--DDL 
--create
---alter -- update modify RENAME DROP
--truncate 
--drop


CREATE TABLE EMPLOYE_DATA (ID NUMBER, NAME VARCHAR(10), LASTNAME VARCHAR(10), MOBILENUMBER NUMBER(10));
INSERT INTO EMPLOYE_DATA(ID, NAME, LASTNAME , MOBILENUMBER, ADDRESS)VALUES(2,'VIRAT', 'KOHLI', 1234567890,'PUNE');

INSERT INTO EMPLOYE_DATA(ID, NAME, LASTNAME , MOBILENUMBER, ADDRESS)VALUES(2,'VIRAT', 'KOHLI', 1234567890,'PUNE');
INSERT INTO EMPLOYE_DATA(ID,NAME,LASTNAME,MOBILENUMBER, ADDRESS)VALUES(3,'RISHABH','PANT',1234509876,'DELHI');

--ALTER TABLE EMPLOYE_DATA MODIFY ADDRESS VARCHAR(10);

INSERT INTO EMPLOYE_DATA VALUES(1,'ROHIT','SHARMA',1234567809,'MUMBAI');
--- ADD USING ALTER
-- WE CAN ADD COLUM IN TABLE
ALTER TABLE EMPLOYE_DATA ADD ADRESS VARCHAR(10);
ALTER TABLE EMPLOYE_DATA ADD COMPANYNAME VARCHAR(10);
---MODIFY
-- WE CAN CHANGE DATA TYPE OFCOLUMN
-- ITS ONLY WORKWHEN TABLE IS EMPTY
ALTER TABLE EMPLOYE_DATA MODIFY MOBILENUMBER NUMBER(20);

--RENMAE
ALTER TABLE EMPLOYE_DATA RENAME COLUMN ADRESS TO ADDRESS;

--DROP 
-- WE AN DROP TABLE AS WELL AS COLUMN
ALTER TABLE EMPLOYE_DATA DROP COLUMN COMPANYNAME;
DROP TABLE EMPLOYE_DATA;
--TRUNCATE
--USED FOR DELETE DATA
TRUNCATE TABLE EMPLOYE_DATA;



DESC EMPLOYE_DATA;
SELECT * FROM employe_data;


-------------------------EXAMPLE--------------

CREATE TABLE STUDENT_INFO (ID NUMBER, NAME VARCHAR(10), LASTNAME VARCHAR(20), CLASSNAME VARCHAR(10), MAKR NUMBER(5));

---UPDATE CL NAME
ALTER TABLE STUDENT_INFO RENAME COLUMN MAKR TO MARK;

INSERT INTO
            STUDENT_INFO (ID, NAME , LASTNAME , CLASSNAME, MARK)
                          VALUE
--                         (1,'ROHOT','SHARMA','10TH',50);
                         (2,'VIRAT','KOHLI','12TH',60),
                         (3,'MAHI','DHONI','FIRESTYEAR',70),
                         (3,'MAHI','DHONI','FIRESTYEAR',70),
                         (3,'MAHI','DHONI','FIRESTYEAR',80);

DESC STUDENT_INFO;
SELECT * FROM STUDENT_INFO;


--------------------------DML------------------
--INSERT 
--UPDATE
--DELETE

---------------------------TCL---------------
--Rollback
--commit
--savepoint


DELETE STUDENT_INFO WHERE ID=1;
ALTER TABLE STUDENT_INFO RENAME COLUMN MARKS TO MARK;
ROLLBACK; //DDL CMD IS AUTOCOMMIT

DELETE STUDENT_INFO WHERE ID=4;
COMMIT;
ROLLBACK; // CANT ROLLBACK COMMIT STMT IT SAVE PERMENTLY

ALTER TABLE STUDENT_INFO ADD ADRESS VARCHAR(10); 
DELETE STUDENT_INFO WHERE ID=3;
DELETE STUDENT_INFO WHERE ID=2;
ROLLBACK;

--SAVEPOINT 
DELETE STUDENT_INFO WHERE ID=3;
SAVEPOINT A;
DELETE STUDENT_INFO WHERE ID=2;
SAVEPOINT B;
INSERT INTO STUDENT_INFO VALUES(5,'VIRENDRA','JADEJA','SE',70,'PUNE');

ROLLBACK TO B; --IT WILL PRINT BLOW RECORD OF SAVEPOINT
ROLLBACK TO A;
ROLLBACK; -- IF YOU RU ROLLBACK IT MEANS IT WILL ROLLBACK ALL DML STMT
-- IT YOU WANT ROLLBACK FIRST RECORD WITH SAVE POINT THEN YOU HAVE CREATE SAVEPOINT AT THE STARTING

SAVEPOINT C;
DELETE STUDENT_INFO WHERE ID=3;
SAVEPOINT A;
DELETE STUDENT_INFO WHERE ID=2;
SAVEPOINT B;
INSERT INTO STUDENT_INFO VALUES(5,'VIRENDRA','JADEJA','SE',70,'PUNE');

ROLLBACK TO C; --IT WILL ROLLBACK ALL RECORD BECAUSE U HAVE WRITE AT THE TOP


DESC STUDENT_INFO;
SELECT * FROM STUDENT_INFO;




