--SUDOCOLUMNS

--CURRENTVAL
--NEXTVAL
--CURRENT DATE
-- SYSDATE
--DATETIMESTAMP
--ROWNUM
--ROWID
--

SELECT STUDENTSQE.CURRVAL FROM DUAL;

CREATE SEQUENCE STUDENTSQE -- Current Value - 5000
MINVALUE 1 
MAXVALUE 5001 
INCREMENT BY 1
START WITH 4
CACHE 20 
NOORDER  
CYCLE ;



CREATE SEQUENCE SQEID
START WITH 5
INCREMENT BY 1
MINVALUE 1
MAXVALUE  1000
CYCLE;



INSERT INTO STUDENT_INFO (ID,NAME,LASTNAME,CLASSNAME,STUD_MARK)VALUES(SQEID.NEXTVAL,'RUSHI','DESAI','2ND',50);
INSERT INTO STUDENT_INFO (ID,NAME,LASTNAME,CLASSNAME,STUD_MARK)VALUES(SQEID.NEXTVAL,'RAN','DESAI','2ND',20);


SELECT * FROM STUDENT_INFO;


CREATE TABLE EMPLOYEE (ID NUMBER , EMP_NAME VARCHAR(10), JOINDATE DATE);

CREATE SEQUENCE EMPID
START WITH 1
INCREMENT BY 1
MAXVALUE 1000
MINVALUE 1
CYCLE;

INSERT INTO EMPLOYEE (ID,EMP_NAME,JOINDATE) VALUES(EMPID.NEXTVAL, 'RUSHI',SYSDATE);

CREATE SEQUENCE PRATIKSHA
MINVALUE 1
MAXVALUE 55
START WITH 1
INCREMENT BY 1
CYCLE;

INSERT INTO  EMPLOYEE (ID, EMP_NAME, JOINDATE) VALUES(PRATIKSHA.NEXTVAL,'RUSHI',SYSDATE);



SELECT * FROM EMPLOYEE;

TRUNCATE TABLE EMPLOYEE;
DROP SEQUENCE PRATIKSHA;


CREATE SEQUENCE  CAR1
MINVALUE 1
MAXVALUE 200
INCREMENT BY 1
START WITH 1
CYCLE;

CREATE TABLE CAR (CARID NUMBER , NAME VARCHAR(10) );
ALTER TABLE CAR RENAME COLUMN NAME TO CARNAME;
INSERT INTO CAR (CARID,CARNAME ) VALUES(CAR1.NEXTVAL , 'SUZU');


SELECT * FROM CAR;


---ROWNUM --TEMP FOR ROW IF U DELETE ROW THAT ROW ID ALLOCATED OR ASSIGN TO NEW ROW

SELECT ROWNUM FROM DUAL;
SELECT ROWNUM , EMP_NAME FROM  EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE ROWNUM=5;
SELECT * FROM EMPLOYEE WHERE ROWNUM<=5;
SELECT * FROM EMPLOYEE WHERE ROWNUM<=9 AND ROWNUM>=5; // NEED TO CHECK AGAIN
SELECT * FROM EMPLOYEE;


---ROWID -- PERMENT FOR ROW IF U DELETE ROW ROWID ALSO DELETED
SELECT ROWID , EMP_NAME FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT SYSDATE FROM DUAL;


SELECT 100+NULL FROM DUAL;


SELECT SALARY+(COMMISSION_PCT*100) FROM EMPLOYEES;



----------------ROWID
SELECT ROWID FROM DUAL;
SELECT ROWNUM FROM DUAL;


--ROWID
SELECT ROWID ,ID, EMP_NAME FROM EMPLOYEE;
DELETE FROM EMPLOYEE  WHERE ID = 49;



---ROWNUM

SELECT ROWNUM , ID , EMP_NAME FROM EMPLOYEE;
DELETE FROM EMPLOYEE  WHERE ID = 50;

SELECT * FROM EMPLOYEE WHERE ROWNUM >=3 ;

SELECT * FROM EMPLOYEE;
------------------------------GROUP BY------------

SELECT EMPLOYEE_ID ,MAX (SALARY) FROM EMPLOYEES GROUP BY EMPLOYEE_ID;

SELECT DEPARTMENT_ID , MAX (SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID ;

SELECT MAX( SUM(AVG(SALARY)) )FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID; // WE CNT PERFORMN OP ON 3 RD LEVEL

SELECT DEPARTMENT_ID , SUM(SALARY)  FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,101,103)
GROUP BY DEPARTMENT_ID
HAVING SUM(SALARY)>9000;        --USED FOR GRP BY RESULT FILTER

SELECT DEPARTMENT_ID , SUM(SALARY)  FROM EMPLOYEES 
WHERE EMPLOYEE_ID IN (100,101,103)
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID>90;   


SELECT * FROM EMPLOYEES;


SELECT * FROM DEPARTMENTS;



SELECT EMPLOYEE_ID , SUM (SALARY +( NVL(COMMISSION_PCT,0)*100)) FROM EMPLOYEES
GROUP BY EMPLOYEE_ID;


SELECT * FROM EMPLOYEES;





from dual);